name: hello          # Name of the workflow

on: [push]           # Triggers when code is pushed to any branch

jobs:                # Defines jobs to run
  say_hello:         # Job ID
    name: Build and Test  # Display name for the job
    runs-on: ubuntu-latest  # Runs on GitHub's Ubuntu runner
    steps:
      - name: Checkout code   # Step name
        run: echo "Hello IDRISS NADIII"  # Command to execute
